### ISSUE TITLE
Refactor: Project + Extension Manifests

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#1057]
Technical Council discussion: https://github.com/polywrap/technical-council/issues/52
# Polywrap Project Manifest Refactor
## Current State
Currently, Polywrap supports the following manifest files:
`polywrap.yaml`: Used for wasm wrapper &amp; interface projects.
`polywrap.plugin.yaml`: Used for plugin wrapper project.
`polywrap.app.yaml`: Used for application projects.
`polywrap.build.yaml`: Customizes the build processed used for wasm wrappers.
`polywrap.deploy.yaml`: Defines the deployment process used for wasm wrappers &amp; interfaces.
`polywrap.meta.yaml`: Defines metadata for a wasm wrapper (description, repository, icon, etc).
`polywrap.infra.yaml`: Defines custom docker containers used by the wrapper.

## Problem
It is not clear which of these manifests are used to define a project, and which ones are “extensions” or “customizations” to that project.

#### Common Properties
```yaml
format: 0.1
project:
  name: foo-bar
  type: wasm/... | interface | plugin/... | app/...
```

#### Wasm
`polywrap.yaml`
```yaml
format: 0.1
project:
  name: foo-bar
  type: wasm/assemblyscript
source:
  schema: ./schema.graphql
  module: ./Cargo.toml
```

#### Interface
`polywrap.yaml`
```yaml
format: 0.1
project:
  name: bizz-buzz
  type: interface
source:
  schema: ./schema.graphql
```

#### Plugin
`polywrap.yaml`
```yaml
format: 0.1
project:
  name: my-plugin
  type: plugin/typescript
source:
  schema: ./schema.graphql
  module: ./src/index.ts
```

#### App
`polywrap.yaml`
```yaml
format: 0.1
project:
  name: my-plugin
  type: app/typescript
source:
  schema: ./schema.graphql
```

### Project Extensions
Every project type (wasm, interface, plugin, app) has a set of supported extension types: build, infra, meta, deploy, codegen.

For example:
```yaml
format: ...
project:
  name: ...
  type: wasm/rust
source:
    schema: ...
    module: ...
extensions:
  build: ./polywrap.build.yaml
  infra: ./polywrap.infra.yaml
  deploy: ./polywrap.deploy.yaml
  meta: ./polywrap/metadata.yaml
```

## Notable Codebase Changes
- We need to decouple the `wasm` & `interface` project types within the codebase
- interface versions = major + minor

### Version Pinning: CLI + Runtime
```yaml
format: 0.1
project:
  ...
  versions:
    polywrap: 1.2.3  #cli version
    wrap: 1.2+origin #wrap version
source:
  schema: ./schema.graphql
```
- `polywrap build`
    - checks `project.versions.polywrap` version
- retarget your codegen/compilation to different wrap runtimes

### Different Extension Manifests
Can now support multiple manifests per extension:
```yaml
...
extensions:
  build:
    debug: ./manifests/polywrap.build.debug.yaml
    prod: ./manifests/polywrap.build.prod.yaml
```

`polywrap build ./polywrap.yaml --type debug`
`polywrap build debug ./polywrap.yaml`

### Inline Extension Manifests
```yaml
...
extensions:
  build:
    format: 0.2
    docker:
      ...
```
