### ISSUE TITLE
Workflows: Unable To Access Nested Result Properties

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#1101]
Given the example below:
```yaml
name: e2e
jobs:
  generate:
    steps:
      - uri: fs/build
        method: generate
    jobs:
      outputImage:
        steps:
          - uri: wrap://ens/fs.polywrap.eth
            method: writeFile
            args:
              path: "./workflows/output.bmp"
              data: "$generate.0.data.content"
```
The final line where we access `$generate.0.data.content` does not work, and we're unable to access this nested property on the result data.
