### ISSUE TITLE
ENS Recursive name registration not setting resolver address for subdomain on public testnet

### ISSUE THREAD

**Issue by namesty** [Web3-API/prototype#1300]
I noticed while using deploy manifest that it's not setting the resolver address for the subdomains.
Manifest:
```yaml
format: "0.2.0"
jobs:
  test:
    config:
      provider: $IPFS_GATEWAY_URI
      gatewayUri: $IPFS_GATEWAY_URI
      ensRegistryAddress: $ENS_REG_ADDR
      ensRegistrarAddress: $ENS_REGISTRAR_ADDR
      ensResolverAddress: $ENS_RESOLVER_ADDR
    steps:
      - name: ipfs_deploy
        package: ipfs
        uri: fs/./build
      - name: ens_register
        package: ens-recursive-name-register
        uri: wrap://ens/goerli/demo.concurrent.polywrap.eth
        config:
          provider: $PROVIDER
          privateKey: $PRIVATE_KEY
      - name: from_deploy2
        package: ens
        uri: $$ipfs_deploy
        config:
          domainName: demo.concurrent.polywrap.eth
          provider: $PROVIDER
          privateKey: $PRIVATE_KEY
          ensRegistryAddress: $ENS_REG_ADDR
          ensRegistrarAddress: $ENS_REGISTRAR_ADDR
          ensResolverAddress: $ENS_RESOLVER_ADDR
```

Log:

```bash
$ npx polywrap deploy
⠋ Load manifest extension from ./.polywrap/wasm/deploy/modules/ipfs/polywrap.deploy.ext.json⠋ Load manifest extension from ./.polywrap/wasm/deploy/modules/ens-recursive-name-register/polywrap.deploy.ext.json⠋ Loa
✔ Load manifest extension from ./.polywrap/wasm/deploy/modules/ens-recursive-name-register/polywrap.deploy.ext.json
✔ Load manifest extension from ./.polywrap/wasm/deploy/modules/ens/polywrap.deploy.ext.json


Executing 'test' deployment DeployJob: 

- ipfs_deploy
- ens_register
- from_deploy2


Executing step: 'ipfs_deploy', with URI: 'wrap://fs/./build'
Successfully executed step 'ipfs_deploy'. Result: 'wrap://ipfs/QmYupBEhDYQ27r9pjCQPis8z4ano2orP3fb7EMv5oCc7Da'
Executing step: 'ens_register', with URI: 'wrap://ens/goerli/demo.concurrent.polywrap.eth'
Successfully executed step 'ens_register'. Result: 'wrap://ens/goerli/goerli/demo.concurrent.polywrap.eth'
Executing step: 'from_deploy2', with URI: 'wrap://ipfs/QmYupBEhDYQ27r9pjCQPis8z4ano2orP3fb7EMv5oCc7Da'
/Users/niraj/Documents/Projects/polywrap/integrations/system/concurrent/implementations/promise/src/__tests__/integration/node_modules/gluegun/build/index.js:13
    throw up;
    ^
Error: Failed to execute step 'from_deploy2'. Error: Error: Resolver not set for 'demo.concurrent.polywrap.eth'
    at DeployJob.<anonymous> (/Users/niraj/Documents/Projects/polywrap/integrations/system/concurrent/implementations/promise/src/__tests__/integration/node_modules/polywrap/build/lib/deploy/job.js:116:31)
    at step (/Users/niraj/Documents/Projects/polywrap/integrations/system/concurrent/implementations/promise/src/__tests__/integration/node_modules/polywrap/build/lib/deploy/job.js:44:23)
    at Object.throw (/Users/niraj/Documents/Projects/polywrap/integrations/system/concurrent/implementations/promise/src/__tests__/integration/node_modules/polywrap/build/lib/deploy/job.js:25:53)
    at rejected (/Users/niraj/Documents/Projects/polywrap/integrations/system/concurrent/implementations/promise/src/__tests__/integration/node_modules/polywrap/build/lib/deploy/job.js:17:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```
