### ISSUE TITLE
Able To Run `polywrap deploy` w/o `polywrap.yaml` Manifest

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#1426]
**Describe the bug**
Currently developers need a valid `polywrap.yaml` project manifest defined in order to run `polywrap deploy`.

**Please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Have a wrapper URI that's pre-built (ex: `/ipfs/QmfRCVA1MSAjUbrXXjya4xA9QHkbWeiKRsT7Um1cvrR7FY`)
- Create a `polywrap.deploy.yaml` manifest that deploys the wrapper, for example:
```yaml
format: 0.1.0
stages:
  ipfs_deploy:
    package: ipfs
    uri: fs/./build
    config:
      gatewayUri: "https://ipfs.wrappers.io"
```
- Try to run `polywrap deploy` in the director of `polywrap.deploy.yaml`, it will fail because no `polywrap.yaml` file is found.

**Expected behavior**
Users should be able to run `polywrap deploy` and only need a `polywrap.deploy.yaml` manifest defined.
