### ISSUE TITLE
CLI version 0.10.4 and 0.10.5 produce `wasm-bindgen` TypeScript artifacts when building Rust Wasm wrap

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#1794]
**Describe the bug**
CLI versions 0.10.4 and 0.10.5 produce `wasm-bindgen` TypeScript artifacts when building Rust Wasm wrap. Clearing the docker cache does not fix the issue. The wrappers are still working and can be invoked.

TODO:

- [x] check if it happens with `0.10.4`
- [x] clear docker cache with `docker system prune --all --volumes`

**Please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Clone https://github.com/polywrap/wrap-abi-bindgen.git
2. Checkout branch `kris/wrap-0.1`
3. navigate to the `implementations/app-typescript` directory
4. In `package.json`, change the `polywrap` and `@polywrap/schema-parse` dependency versions to `0.10.5`
5. run `nvm use && yarn && yarn build`
6. The unexpected artifacts can be found in the `build` folder

**Expected behavior**
All `wasm-bindgen` should be removed by `wasm-snip`

**Screenshots / logs**
<img width="219" alt="Screenshot 2023-06-28 at 10 48 21 AM" src="https://github.com/polywrap/cli/assets/39842820/33b66b6d-7349-4c0d-b3f5-067599693dba">
<img width="194" alt="Screenshot 2023-06-28 at 10 49 43 AM" src="https://github.com/polywrap/cli/assets/39842820/73bbd8d6-c8a5-435e-bd16-584851535344">
<img width="439" alt="Screenshot 2023-06-28 at 10 49 52 AM" src="https://github.com/polywrap/cli/assets/39842820/0d01d464-f521-4964-a8be-3d76ac319418">
<img width="539" alt="Screenshot 2023-06-28 at 10 49 59 AM" src="https://github.com/polywrap/cli/assets/39842820/693914cb-6d4c-4a78-99de-694155535924">
<img width="358" alt="Screenshot 2023-06-28 at 10 50 06 AM" src="https://github.com/polywrap/cli/assets/39842820/75770995-f4ed-49f9-9ac5-50fdac095c5d">

The wrap's Rust dependencies:
```toml
[dependencies]
polywrap-wasm-rs = { version = "~0.10.5" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.97" }
handlebars = { version = "4.3.7" }
lazy_static = { version = "1.4.0" }
regex = { version = "1.8.4" }
```

**Relevant environment details:**
- OS: Mac OS

**Additional context**
I am aware that this also occurred when building the `ethers-utils` wrap found here: https://github.com/polywrap/ethers/tree/main/wraps/utils
