### ISSUE TITLE
Web3API Publisher Metadata

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#181]
For the Web3Hub, we want to enable Web3API developers the ability to define various pieces of metadata that will show up on their Web3Hub page. We could call this file `web3api.publish.yaml`, which might fit nicely alongside the other manifest files (defined: `web3api.yaml`, `web3api.build.yaml`, `web3api.env.yaml`) (planned: `web3apy.test.yaml`, `web3api.deploy.yaml`).

Here's a rough sketch of what this might look like:
![unknown](https://user-images.githubusercontent.com/5522128/109708402-5ef79b00-7b69-11eb-997a-6ddef8a3ea4b.png)

Ideally the Web3Hub (and any other app) could query this file through the Web3API client. A possible way to do this might be:
```typescript
const api = await client.resolve({ api: "ens/some.api.eth" });
const metadata = api.getFile(api.manifest.publish.file);
```

**Comment by dOrgJelli** [comment]
Some more ideation:
`web3api.content.yaml`
```
icon: ./content/icon.png
name: ...
description: ...
links:
  - name: ...
    icon: ...
    url: ...
query-templates:
  - name: Create Wallet
    query: ./templates/create-wallet.graphql
```

This will make its way into the build folder like so:
```
/build
  - web3api.yaml
  - web3api.content.yaml
  /content
    - icon.png
  /templates
    - create-wallet.graphql
```

A problem that exists with this approach is that it requires republishing the package in order to change the content, since everything will be uploaded to IPFS.

In the future we can solve this problem by using dynamic links for the content, like IPNS hashes for example.

**Comment by dOrgJelli** [comment]
This is a blocker for the Web3Hub's development.

**Comment by dOrgJelli** [comment]
I've created an example project that contains a `web3api.meta.yaml` manifest file here: https://github.com/Web3-API/demos/tree/main/simple-storage/web3api

The schema I came up with is as follows:
```yaml
name: SimpleStorage (ETH)
description: SimpleStorage Web3API Using Ethereum
icon: ./meta/imgs/web3api.svg
banner: ./meta/imgs/web3api-banner.svg
links:
  - name: GitHub
    icon: ./meta/imgs/github.svg
    url: https://github.com/Web3-API/demos/tree/main/simple-storage/web3api
  - name: Website
    icon: ./meta/imgs/web3api.svg
    url: https://web3api.dev
queries:
  - name: Deploy Storage Contract
    description: Deploy the SimpleStorage contract onto Ethereum.
    query: ./meta/queries/deploy.graphql
  - name: Get Storage Value
    description: Get the storage value within an existing SimpleStorage contract on Ethereum.
    query: ./meta/queries/get.graphql
  - name: Set Storage Value
    description: Set the storage value within an existing SimpleStorage contract on Ethereum.
    query: ./meta/queries/set.graphql
```

Things left to do:
- [ ] Implement schema sanitization for this new manifest file (depends upon https://github.com/Web3-API/monorepo/issues/207)
- [ ] Move the meta manifest and all referenced files into the build folder
- [ ] Ensure there's an easy way to fetch this information through the Web3API client (initial example interface written above)
