### ISSUE TITLE
Polywrap Manifest: Make use of defaults

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#1909]
# Manifest: Make use of defaults

When it comes to developing a wrap, the user needs to define a `polywrap.yaml` manifest; in this manifest is necessary that the `module` and `schema` are defined. This actually may be simplified. The user should not need to define those unless it has some custom name or path (which is actually very rare).

We need to implement defaults per language and make the build process smart enough to find the needed files if not given

## Today's Devexp
```yaml
format: 0.5.0
project:
  name: asyncify
  type: wasm/rust
source:
  schema: ./polywrap.graphql
  module: ./Cargo.toml
```

## Tomorrow's Devexp
```yaml
format: 0.5.0
project:
  name: asyncify
  type: wasm/rust
```
