### ISSUE TITLE
Uniswap demo: "Unrecognized manifest schema format "undefined"

### ISSUE THREAD

**Issue by kev-ngo** [Web3-API/prototype#321]
# Issue
I'm trying to use a Uniswap Web3API query but receive the following message in my console:
`"Unrecognized manifest schema format "undefined""`

# What I've tried
Adding this to the manifest file and re-building:

```yml
import_redirects:
  - uri: w3://ens/ethereum.web3api.eth
    schema: ../../js/plugins/ethereum/schema.graphql
  - uri: w3://ens/ipfs.web3api.eth
    schema: ../../js/plugins/ipfs/schema.graphql
```

# Steps to reproduce

## Deploy the Uniswap Web3API to Ipfs on localhost

1. Open the Web3API `monorepo`, pull the `uniswap-web3api` branch, and change to the `uniswapv2` directory.

```
git checkout -b uniswap
git pull origin uniswap-web3api
cd packages/apis/uniswapv2
```

2. Add the following script into the `package.json` file:
`"deploy": "w3 build --ipfs http://127.0.0.1:5001"`

3. In the `uniswapv2` folder, install dependencies and then deploy to Ipfs:

```
yarn
yarn deploy
```

The CLI will generate a Ipfs address.  We'll be using this later.

## Web3API integration into the Uniswap Interface
1. In a separate VScode, clone the Uniswap Interface (monorepo-issue-321 branch) and start up the dApp:

```
git clone git@github.com:Web3-API/uniswap-interface.git
cd uniswap-interface
git pull origin monorepo-issue-321
yarn
yarn start
```

2. I've set up the Web3ApiProvider in `src/components/Web3ReactManager/index.tsx`

3. In the `src/pages/Swap/index.tsx file`, copy and paste the Ipfs hash into `Qm<Hash>` inside the `useWeb3ApiQuery` custom hook.

4. Take a look at your console in Chrome/Brave for `testWeb3API`.

<img width="614" alt="1" src="https://user-images.githubusercontent.com/69411313/116797710-90bfac00-aa9d-11eb-9708-345a49a24d1d.png">
