### ISSUE TITLE
Manifest Formatting Options

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#45]
Option 1:
```yaml
api:
  schema:
    file: ./src/mutation/schema.graphql
  schemas:
    - file: ./src/mutation/schema.graphql
    - file: ./src/query/schema.graphql
  mutation:
    language: wasm/assemblyscript
    file: ./src/mutation/index.ts
  query:
    language: wasm/assemblyscript
    file: ./src/query/index.ts
```

Option 2:
```yaml
apis:
  - namespace: "cool-storage"
    schemas:
      - file: ./src/mutation/schema.graphql
      - file: ./src/query/schema.graphql
    mutation:
      language: wasm/assemblyscript
      file: ./src/mutation/index.ts
    query:
      language: wasm/assemblyscript
      file: ./src/query/index.ts
  - namespace: "sub-storage"
    schemas:
      - file: ./src/mutation/schema.graphql
      - file: ./src/query/schema.graphql
    mutation:
      language: wasm/assemblyscript
      file: ./src/mutation/index.ts
    query:
      language: wasm/assemblyscript
      file: ./src/query/index.ts
```
