### ISSUE TITLE
Create New "Source" Manifest File

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#644]
Create a new `web3api.source.yaml` manifest file, that includes properties relevant to the source files used to build the wasm modules. An example schema might be:
```yaml
build_image:
  path: ...
  hash: ...
toolchain:
  version: 0.0.1-prealpha.60
```
