### ISSUE TITLE
Refined Plugin Import Semantics

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#724]
We must refine how we're treating plugins within the toolchain.

### Option 1: Inline Plugin Definition
Within the project's schema, define the plugin dependency's schema in-line:
```graphql
type HTTP_Query @plugin(uri: "plugin/http") {
  method: String!
}
```

### Option 2: External Plugin Import
Within the project's schema, import types from the plugin's externally available schema:
```graphql
#import { Query } into HTTP from "plugin/http"
```
and in order to resolve the `"plugin/http"` URI, the developer must utilize the `import_redirects` manifest property like so:
```yaml
import_redirects:
  - uri: "plugin/http"
    schema: ./node_modules/http-plugin/schema.graphql
```
additionally an interface URI could be used like so:
```yaml
import_redirects:
  - uri: "plugin/http"
    interface: "ens/http-plugin-interface.eth"
```

### In-Line Schema Redirects?
```graphql
#plugin { Query } into HTTP at "plugin/http" from "ens/http-plugin-interface.eth"

#import { Query } into HTTP from "ens/http-plugin-interface.eth" at "plugin/http"
```

### "plugins:" Manifest Property?
```yaml
plugins:
  - uri: "plugin/http"
    schema: ./node_modules/http-plugin/schema.graphql

  - uri: "plugin/other"
    interface: "ens/other-interface.eth"
```
