### ISSUE TITLE
app/react App Codegen Language Type

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#730]
Add support for the `app/react` codegen language type, specified in the `web3api.app.yaml` manifest file like so:
```yaml
format: ...
language: app/react
schema: ...
```

What exactly the resulting codegen will look like is still TBD, will need some discussion here to decide on this before this task is implemented.
