### ISSUE TITLE
Add default modules capability to Infra Manifest

### ISSUE THREAD

**Issue by namesty** [Web3-API/prototype#909]
Currently, default modules such as `eth-ens-ipfs` cannot be declared in the `infra` manifest. So if one wanted to orchestrate a combination of default environments + manifest declared environments, it would require a syntax such as:

`w3 infra up --modules=eth-ens-ipfs,manifestmodule1,manifestmodule2, ...` and so on enumerating all manifest declared modules. This is not only not intuitive, but very cumbersome.

Therefore, we require adding a new type of infra manifest module (we currently have `RemoteModule` and `LocalModule`) which would represent default-available modules, something like `DefaultModule`.

With that, users would be able to declare default modules in the infra manifest as normal, like

```yaml
modules:
  eth-ens-ipfs: default
  mainnet-fork:
    path: ...
```

or

```yaml
modules:
  eth-ens-ipfs
  mainnet-fork:
    path: ...
```
